#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../../lib/bowenos/includes/common.sh
source "${SCRIPT_DIR}/../../lib/bowenos/includes/common.sh"

nix build "${ROOT}#iso"
