#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../../lib/bowenos/includes/common.sh
source "${SCRIPT_DIR}/../../lib/bowenos/includes/common.sh"

if [[ -f /etc/bowenos/flake.nix ]]; then
  HOST="$(cat /etc/hostname)"
  ensure_mountpoint /boot "disk-bootA-esp"
  if [[ -e /dev/disk/by-partlabel/disk-bootB-esp ]]; then
    ensure_mountpoint /bootB "disk-bootB-esp"
  fi
  sudo nixos-rebuild switch --refresh --impure --flake "path:/etc/bowenos#${HOST}"
else
  echo "Missing /etc/bowenos" >&2
  exit 1
fi
